fix/ryme-13-fix-pagination-characters
Ambrusecoding/rick-and-morty pull request #2
Opened 2024-02-27 20:26 UTC by Ambrusecoding

## Explicación del problema 

Fixed an error that the pagination was having on the home page

### Issues Relacionados

❌ Paginación RYM-02

## Qué se hizo para solucionar el problema?

### Screenshots

![image](https://github.com/Ambrusecoding/rick-and-morty/assets/111497104/0230c9b6-b5ea-48af-8263-521c520c8600)

If you activated the filters while on the last page, it would not be filtered and the information would not be displayed

## Cómo probar el cambio?

Performing the action named above

2024-02-27 21:04 UTC, Camiloadh99 requested changes

2024-02-27 21:04 UTC, Camiloadh99 commented on src/pages/home/index.tsx
> +  React.useEffect(() => {
Recuerda que lo mejor es dejar esto sin el React.

2024-02-27 21:04 UTC, Camiloadh99 commented on src/pages/home/index.tsx
> +  }, [filter]);
Seguro es algo que se puede evitar el useEffect

2024-02-28 11:07 UTC, Ambrusecoding commented on src/pages/home/index.tsx
> +  }, [filter]);
Done

2024-02-28 11:07 UTC, Ambrusecoding commented on src/pages/home/index.tsx
> +  React.useEffect(() => {
Done

2024-02-28 15:44 UTC, Camiloadh99 approved these changes

2024-02-28 15:44 UTC, Camiloadh99 commented on src/pages/home/index.tsx
> +        />
nice!
depues te enseño una forma  para optimizar estos filtros!

2024-02-29 13:19 UTC, merged