feature/rym-11-local-storage-favorite-characters
Ambrusecoding/rick-and-morty pull request #3
Opened 2024-02-27 20:38 UTC by Ambrusecoding

## Explicación del problema 

Anteriormente al actualizar la pagina, no se estaban guardando los personajes favoritos en el local storage 

### Issues Relacionados
RYM-11 
RYM-12

## Qué se hizo para solucionar el problema?
Se implementó la funcionalidad de LocalStorage en el archivo donde se maneja el redux

### Screenshots
![image](https://github.com/Ambrusecoding/rick-and-morty/assets/111497104/b033982d-c6fd-424f-95cd-2e8a971963a9)

![image](https://github.com/Ambrusecoding/rick-and-morty/assets/111497104/b673128d-3264-43de-9e4b-16c950bb0138)

## Cómo probar el cambio?

Agregar personajes a como favoritos y recargar la pagina. Comprobar que los que hayan sido agregados permanezcan y los que hayan sido eliminados no estén

2024-02-27 21:12 UTC, Camiloadh99 requested changes

2024-02-27 21:12 UTC, Camiloadh99 commented on src/redux/slices/character.slice.ts
> +  JSON.parse(localStorage.getItem("favoriteCharacters") ?? "") || [];
magic string, los keys deberian estar en un objeto para llamar solo su key

2024-02-27 21:12 UTC, Camiloadh99 commented on src/redux/slices/character.slice.ts
> +      const index = state.findIndex((item) => item.id === id);
el nombre no me dice nada index de que ?

2024-02-27 21:12 UTC, Camiloadh99 commented on src/redux/slices/character.slice.ts
> +      localStorage.setItem("favoriteCharacters", JSON.stringify(state));
magic string, debe ser un objeto de los keys de local storage

2024-02-28 11:20 UTC, Ambrusecoding commented on src/redux/slices/character.slice.ts
> +      const index = state.findIndex((item) => item.id === id);
done

2024-02-28 11:20 UTC, Ambrusecoding commented on src/redux/slices/character.slice.ts
> +  JSON.parse(localStorage.getItem("favoriteCharacters") ?? "") || [];
done

2024-02-28 11:20 UTC, Ambrusecoding commented on src/redux/slices/character.slice.ts
> +      localStorage.setItem("favoriteCharacters", JSON.stringify(state));
no lo entendí muy bien

2024-02-28 15:45 UTC, Camiloadh99 approved these changes
super!

2024-02-29 13:20 UTC, merged