feature/rym-10-add-internal-page-episode
Ambrusecoding/rick-and-morty pull request #4
Opened 2024-02-27 21:00 UTC by Ambrusecoding

## Explicación del problema

No había sido creada la página de información de cada episodios.

### Issues Relacionados
RYM-10
https://app.asana.com/0/1206613979557024/1206613979557003/f

## Qué se hizo para solucionar el problema?

Se creó la página interna con los requisitos solicitados

### Screenshots

Antes: 

![image](https://github.com/Ambrusecoding/rick-and-morty/assets/111497104/d53f6ea2-4b0c-41e3-9184-abb4f3692e6f)

Después: 

![image](https://github.com/Ambrusecoding/rick-and-morty/assets/111497104/69328ab7-6d65-4b57-a47a-889f9dc84066)

## Cómo probar el cambio?

Entrar  al tab de episodios y posterior a eso seleccionar el Botón de más información para entrar a la página interna de cada episodio 

![image](https://github.com/Ambrusecoding/rick-and-morty/assets/111497104/6ae08079-f840-4d22-8cc1-8f2985e97a1b)

2024-02-27 21:19 UTC, Camiloadh99 requested changes

2024-02-27 21:19 UTC, Camiloadh99 commented on src/Router.tsx
> +        <Route path="/episode/:id" element={<EpisodeComponent />} />
magic strings.. xd
Tambien puedes tener un objeto de rutas para no hacer directamente el string si no la key

2024-02-27 21:19 UTC, Camiloadh99 commented on src/api/episode.ts
> +    const episodeDataDOM: TypeEpisodeDOM = {
El adaptador debe ir en una funcion aparte 
es importante dividir resposnabilidades

2024-02-27 21:19 UTC, Camiloadh99 commented on src/api/episode.ts
>  };
Recuerda el custom hook

2024-02-27 21:19 UTC, Camiloadh99 commented on src/pages/internalEpisode/index.tsx
> +  React.useEffect(() => {
El React. no va

2024-02-27 21:19 UTC, Camiloadh99 commented on src/pages/internalEpisode/index.tsx
> +  const [episode, setEpisode] = React.useState<TypeEpisodeDOM | null>(null);
React. no va

2024-02-27 21:19 UTC, Camiloadh99 commented on src/pages/internalEpisode/index.tsx
> +  }, [id]);
ya hablamos de los then entonces no deberia tenerlos aqui

2024-02-28 11:29 UTC, Ambrusecoding commented on src/pages/internalEpisode/index.tsx
> +  const [episode, setEpisode] = React.useState<TypeEpisodeDOM | null>(null);
done

2024-02-28 11:30 UTC, Ambrusecoding commented on src/pages/internalEpisode/index.tsx
> +  React.useEffect(() => {
done

2024-02-28 11:30 UTC, Ambrusecoding commented on src/pages/internalEpisode/index.tsx
> +  }, [id]);
done

2024-02-28 11:33 UTC, Ambrusecoding commented on src/Router.tsx
> +        <Route path="/episode/:id" element={<EpisodeComponent />} />
DONE

2024-02-28 14:56 UTC, Ambrusecoding commented on src/api/episode.ts
> +    const episodeDataDOM: TypeEpisodeDOM = {
Done

2024-02-28 15:47 UTC, Camiloadh99 requested changes

2024-02-28 15:47 UTC, Camiloadh99 commented on src/Router.tsx
> +  };
lo mejor es en archivo aparte pero esta bien la idea

2024-02-28 15:47 UTC, Camiloadh99 commented on src/pages/internalEpisode/index.tsx
> +        setTimeout(() => setLoading(false), 1000);
waittt y esto por que??? este timeout no entiendo su funcion

2024-02-29 13:32 UTC, closed without merging